--------------------------------------------------------
--  文件已创建 - 星期二-九月-22-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CHANGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."CHANGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence HISTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."HISTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence LEAVE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."LEAVE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence MANAGER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."MANAGER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence OCCUPATIONCAREER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."OCCUPATIONCAREER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SKDEPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SKDEPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SKEMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SKEMP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SKJOB_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SKJOB_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SKSTAFF_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SKSTAFF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SOCIETYRELATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SOCIETYRELATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TALENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."TALENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TEMPORARY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."TEMPORARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table CHANGE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CHANGE" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"OLDDEPT" VARCHAR2(20 BYTE), 
	"NEWDEPT" VARCHAR2(20 BYTE), 
	"CHANGREASON" VARCHAR2(20 BYTE), 
	"OLDJOB" VARCHAR2(20 BYTE), 
	"NEWJOB" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CHANGTIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."HISTORY" 
   (	"ID" NUMBER(*,0), 
	"DEPT_ID" VARCHAR2(10 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PEOPLENUM" NUMBER(*,0), 
	"CHANGETIME" VARCHAR2(20 BYTE), 
	"OLDNUM" NUMBER(*,0), 
	"NEWNUM" NUMBER(*,0), 
	"MANGERNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LEAVE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."LEAVE" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"PLACE" VARCHAR2(20 BYTE), 
	"TIME" VARCHAR2(20 BYTE), 
	"REASON" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MANAGER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OCCUPATIONCAREER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."OCCUPATIONCAREER" 
   (	"ID" NUMBER(*,0), 
	"BEGINTIME" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(20 BYTE), 
	"JOBNAME" VARCHAR2(50 BYTE), 
	"JOBDISCRIP" VARCHAR2(1000 BYTE), 
	"POSITION" VARCHAR2(100 BYTE), 
	"SALARY" NUMBER, 
	"REFERENCE" VARCHAR2(100 BYTE), 
	"REFERENCETEL" VARCHAR2(50 BYTE), 
	"REFERENCEPOSITION" VARCHAR2(100 BYTE), 
	"EMP_ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKDEPT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKDEPT" 
   (	"ID" NUMBER(*,0), 
	"DEPT_ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TELE" VARCHAR2(20 BYTE), 
	"FAX" VARCHAR2(20 BYTE), 
	"DISCRIP" VARCHAR2(50 BYTE), 
	"SUPERD" VARCHAR2(10 BYTE), 
	"CREATETIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKEMP
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKEMP" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"SEX" VARCHAR2(10 BYTE), 
	"BIR" VARCHAR2(20 BYTE), 
	"IDCARD" VARCHAR2(30 BYTE), 
	"TOWORKTIME" VARCHAR2(20 BYTE), 
	"ZZMM" VARCHAR2(20 BYTE), 
	"NATIONAL" VARCHAR2(20 BYTE), 
	"NATIV" VARCHAR2(20 BYTE), 
	"TELE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(30 BYTE), 
	"HEIGHT" VARCHAR2(20 BYTE), 
	"BLOODTYPE" VARCHAR2(10 BYTE), 
	"BIRTHPLACE" VARCHAR2(50 BYTE), 
	"HKPLACE" VARCHAR2(50 BYTE), 
	"DEGREE" VARCHAR2(20 BYTE), 
	"GRADUATESCHOOL" VARCHAR2(50 BYTE), 
	"PROFESSIONAL" VARCHAR2(50 BYTE), 
	"GRADUATETIME" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKJOB
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKJOB" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"LIMITNUM" VARCHAR2(10 BYTE), 
	"DEPT_ID" VARCHAR2(10 BYTE), 
	"ISLIMIT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKSTAFF
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKSTAFF" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"TIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOCIETYRELATION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SOCIETYRELATION" 
   (	"ID" NUMBER(*,0), 
	"RELATION" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"JOB" VARCHAR2(20 BYTE), 
	"POSI" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"EMP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TALENT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TALENT" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEMPORARY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TEMPORARY" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"BEGINTIME" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.CHANGE
SET DEFINE OFF;
REM INSERTING into SCOTT.HISTORY
SET DEFINE OFF;
REM INSERTING into SCOTT.LEAVE
SET DEFINE OFF;
REM INSERTING into SCOTT.MANAGER
SET DEFINE OFF;
REM INSERTING into SCOTT.OCCUPATIONCAREER
SET DEFINE OFF;
REM INSERTING into SCOTT.SKDEPT
SET DEFINE OFF;
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (9,'1','总公司','Enterprice','2176003','64275080','行政管理',null,'1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (10,'2','行政部','Enterprice','2176003','64275080','行政管理','0','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (11,'3','生产部','Enterprice','64275087','64275084','产品生产','1','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (8,'0','总经办','Enterprice','2176004','64275060','行政管理',null,'1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (12,'4','技术部','Dept','2176003','64275080','技术设计','3','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (13,'5','销售部','Dept','2176003','64275080','市场销售','3','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (14,'6','财务部','Dept','2176003','64275080','财务','2','1997-08-06');
REM INSERTING into SCOTT.SKEMP
SET DEFINE OFF;
REM INSERTING into SCOTT.SKJOB
SET DEFINE OFF;
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (1,'行政总监','1','Manage','3','2','Yes');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (2,'行政主管','2','Manage','10','4','Yes');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (3,'技术开发','3','Technology','40','4','No');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (4,'销售总监','4','Marketing','30','5','No');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (5,'财务总管','5','Market','10','6','Yes');
REM INSERTING into SCOTT.SKSTAFF
SET DEFINE OFF;
REM INSERTING into SCOTT.SOCIETYRELATION
SET DEFINE OFF;
REM INSERTING into SCOTT.TALENT
SET DEFINE OFF;
REM INSERTING into SCOTT.TEMPORARY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CHANGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CHANGE_PK" ON "SCOTT"."CHANGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."HISTORY_PK" ON "SCOTT"."HISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LEAVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."LEAVE_PK" ON "SCOTT"."LEAVE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MANAGER_PK" ON "SCOTT"."MANAGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANAGER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MANAGER_UK1" ON "SCOTT"."MANAGER" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OCCUPATIONCAREER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."OCCUPATIONCAREER_PK" ON "SCOTT"."OCCUPATIONCAREER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKDEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKDEPT_PK" ON "SCOTT"."SKDEPT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKDEPT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKDEPT_UK1" ON "SCOTT"."SKDEPT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKDEPT_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKDEPT_UK2" ON "SCOTT"."SKDEPT" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKEMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKEMP_PK" ON "SCOTT"."SKEMP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKEMP_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKEMP_UK1" ON "SCOTT"."SKEMP" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKEMP_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKEMP_UK2" ON "SCOTT"."SKEMP" ("IDCARD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKJOB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKJOB_PK" ON "SCOTT"."SKJOB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKJOB_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKJOB_UK1" ON "SCOTT"."SKJOB" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKSTAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKSTAFF_PK" ON "SCOTT"."SKSTAFF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOCIETYRELATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SOCIETYRELATION_PK" ON "SCOTT"."SOCIETYRELATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TALENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TALENT_PK" ON "SCOTT"."TALENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEMPORARY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TEMPORARY_PK" ON "SCOTT"."TEMPORARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CHANGE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CHANGE" ADD CONSTRAINT "CHANGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("CHANGTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("NEWJOB" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("OLDJOB" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("CHANGREASON" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("NEWDEPT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("OLDDEPT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CHANGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("MANGERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" ADD CONSTRAINT "HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("NEWNUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("OLDNUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("CHANGETIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("PEOPLENUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("DEPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."HISTORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LEAVE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."LEAVE" ADD CONSTRAINT "LEAVE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."LEAVE" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."LEAVE" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."LEAVE" MODIFY ("PLACE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."LEAVE" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."LEAVE" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."LEAVE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MANAGER" ADD CONSTRAINT "MANAGER_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."MANAGER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MANAGER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MANAGER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OCCUPATIONCAREER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" ADD CONSTRAINT "OCCUPATIONCAREER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("REFERENCEPOSITION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("JOBDISCRIP" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("JOBNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("BEGINTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKDEPT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_UK2" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_UK1" UNIQUE ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("CREATETIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("FAX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("TELE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("DEPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKEMP
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" ADD CONSTRAINT "SKEMP_UK2" UNIQUE ("IDCARD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKEMP" ADD CONSTRAINT "SKEMP_UK1" UNIQUE ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKEMP" ADD CONSTRAINT "SKEMP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("ZZMM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("TOWORKTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("IDCARD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("BIR" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKJOB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("ISLIMIT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" ADD CONSTRAINT "SKJOB_UK1" UNIQUE ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKJOB" ADD CONSTRAINT "SKJOB_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("DEPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("LIMITNUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKSTAFF
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKSTAFF" ADD CONSTRAINT "SKSTAFF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKSTAFF" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKSTAFF" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKSTAFF" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKSTAFF" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOCIETYRELATION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SOCIETYRELATION" ADD CONSTRAINT "SOCIETYRELATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SOCIETYRELATION" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SOCIETYRELATION" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SOCIETYRELATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SOCIETYRELATION" MODIFY ("RELATION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SOCIETYRELATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TALENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TALENT" ADD CONSTRAINT "TALENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."TALENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TALENT" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TALENT" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TALENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEMPORARY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TEMPORARY" ADD CONSTRAINT "TEMPORARY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."TEMPORARY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEMPORARY" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEMPORARY" MODIFY ("BEGINTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEMPORARY" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEMPORARY" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEMPORARY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CHANGE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CHANGE" ADD CONSTRAINT "CHANGE_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."HISTORY" ADD CONSTRAINT "HISTORY_SKDEPT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "SCOTT"."SKDEPT" ("DEPT_ID") ENABLE;
  ALTER TABLE "SCOTT"."HISTORY" ADD CONSTRAINT "HISTORY_SKJOB_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "SCOTT"."SKJOB" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEAVE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."LEAVE" ADD CONSTRAINT "LEAVE_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
  ALTER TABLE "SCOTT"."LEAVE" ADD CONSTRAINT "LEAVE_SKJOB_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "SCOTT"."SKJOB" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OCCUPATIONCAREER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" ADD CONSTRAINT "OCCUPATIONCAREER_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKDEPT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_SKDEPT_FK1" FOREIGN KEY ("SUPERD")
	  REFERENCES "SCOTT"."SKDEPT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKJOB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKJOB" ADD CONSTRAINT "SKJOB_SKDEPT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "SCOTT"."SKDEPT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKSTAFF
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKSTAFF" ADD CONSTRAINT "SKSTAFF_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
  ALTER TABLE "SCOTT"."SKSTAFF" ADD CONSTRAINT "SKSTAFF_SKJOB_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "SCOTT"."SKJOB" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOCIETYRELATION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SOCIETYRELATION" ADD CONSTRAINT "SOCIETYRELATION_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TALENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TALENT" ADD CONSTRAINT "TALENT_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
  ALTER TABLE "SCOTT"."TALENT" ADD CONSTRAINT "TALENT_SKJOB_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "SCOTT"."SKJOB" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMPORARY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TEMPORARY" ADD CONSTRAINT "TEMPORARY_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
  ALTER TABLE "SCOTT"."TEMPORARY" ADD CONSTRAINT "TEMPORARY_SKJOB_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "SCOTT"."SKJOB" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHANGE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."CHANGE_TRG" BEFORE INSERT ON CHANGE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT CHANGE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."CHANGE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HISTORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."HISTORY_TRG" BEFORE INSERT ON HISTORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT HISTORY_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."HISTORY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LEAVE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."LEAVE_TRG" BEFORE INSERT ON LEAVE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT LEAVE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."LEAVE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MANAGER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."MANAGER_TRG" BEFORE INSERT ON MANAGER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT MANAGER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."MANAGER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OCCUPATIONCAREER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."OCCUPATIONCAREER_TRG" BEFORE INSERT ON OCCUPATIONCAREER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT OCCUPATIONCAREER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."OCCUPATIONCAREER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKDEPT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKDEPT_TRG" BEFORE INSERT ON SKDEPT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKDEPT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKDEPT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKEMP_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKEMP_TRG" BEFORE INSERT ON SKEMP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKEMP_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKEMP_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKJOB_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKJOB_TRG" BEFORE INSERT ON SKJOB 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKJOB_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKJOB_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKSTAFF_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKSTAFF_TRG" BEFORE INSERT ON SKSTAFF 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKSTAFF_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKSTAFF_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SOCIETYRELATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SOCIETYRELATION_TRG" BEFORE INSERT ON SOCIETYRELATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SOCIETYRELATION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SOCIETYRELATION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TALENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."TALENT_TRG" BEFORE INSERT ON TALENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT TALENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TALENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TEMPORARY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."TEMPORARY_TRG" BEFORE INSERT ON TEMPORARY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT TEMPORARY_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TEMPORARY_TRG" ENABLE;
