--------------------------------------------------------
--  文件已创建 - 星期日-九月-20-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OCCUPATIONCAREER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."OCCUPATIONCAREER" 
   (	"ID" NUMBER(*,0), 
	"BEGINTIME" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(20 BYTE), 
	"JOBNAME" VARCHAR2(50 BYTE), 
	"JOBDISCRIP" VARCHAR2(1000 BYTE), 
	"POSITION" VARCHAR2(100 BYTE), 
	"SALARY" NUMBER, 
	"REFERENCE" VARCHAR2(100 BYTE), 
	"REFERENCETEL" VARCHAR2(50 BYTE), 
	"REFERENCEPOSITION" VARCHAR2(100 BYTE), 
	"EMP_ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.OCCUPATIONCAREER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index OCCUPATIONCAREER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."OCCUPATIONCAREER_PK" ON "SCOTT"."OCCUPATIONCAREER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OCCUPATIONCAREER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" ADD CONSTRAINT "OCCUPATIONCAREER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("REFERENCEPOSITION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("JOBDISCRIP" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("JOBNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("BEGINTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OCCUPATIONCAREER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."OCCUPATIONCAREER" ADD CONSTRAINT "OCCUPATIONCAREER_SKEMP_FK1" FOREIGN KEY ("EMP_ID")
	  REFERENCES "SCOTT"."SKEMP" ("EMP_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger OCCUPATIONCAREER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."OCCUPATIONCAREER_TRG" BEFORE INSERT ON OCCUPATIONCAREER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT OCCUPATIONCAREER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."OCCUPATIONCAREER_TRG" ENABLE;
