--------------------------------------------------------
--  文件已创建 - 星期六-九月-19-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SKDEPT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKDEPT" 
   (	"ID" NUMBER(*,0), 
	"DEPT_ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TELE" VARCHAR2(20 BYTE), 
	"FAX" VARCHAR2(20 BYTE), 
	"DISCRIP" VARCHAR2(50 BYTE), 
	"SUPERD" VARCHAR2(10 BYTE), 
	"CREATETIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.SKDEPT
SET DEFINE OFF;
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (1,'1','总公司','Enterprice','2176003','64275080','行政管理',null,'1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (2,'2','行政部','Enterprice','2176003','64275080','行政管理','0','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (3,'3','生产部','Enterprice','64275087','64275084','产品生产','1','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (4,'0','总经办','Enterprice','2176004','64275060','行政管理',null,'1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (5,'4','技术部','Dept','2176003','64275080','技术设计','3','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (6,'5','销售部','Dept','2176003','64275080','市场销售','3','1997-08-06');
Insert into SCOTT.SKDEPT (ID,DEPT_ID,NAME,TYPE,TELE,FAX,DISCRIP,SUPERD,CREATETIME) values (7,'6','财务部','Dept','2176003','64275080','财务','2','1997-08-06');
--------------------------------------------------------
--  DDL for Index SKDEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKDEPT_PK" ON "SCOTT"."SKDEPT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKDEPT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKDEPT_UK1" ON "SCOTT"."SKDEPT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKDEPT_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKDEPT_UK2" ON "SCOTT"."SKDEPT" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SKDEPT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_UK2" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_UK1" UNIQUE ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("CREATETIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("FAX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("TELE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("DEPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKDEPT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SKDEPT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKDEPT" ADD CONSTRAINT "SKDEPT_SKDEPT_FK1" FOREIGN KEY ("SUPERD")
	  REFERENCES "SCOTT"."SKDEPT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKDEPT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKDEPT_TRG" BEFORE INSERT ON SKDEPT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKDEPT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKDEPT_TRG" ENABLE;
