--------------------------------------------------------
--  文件已创建 - 星期日-九月-20-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SKEMP
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKEMP" 
   (	"ID" NUMBER(*,0), 
	"EMP_ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"SEX" VARCHAR2(10 BYTE), 
	"BIR" VARCHAR2(20 BYTE), 
	"IDCARD" VARCHAR2(30 BYTE), 
	"TOWORKTIME" VARCHAR2(20 BYTE), 
	"ZZMM" VARCHAR2(20 BYTE), 
	"NATIONAL" VARCHAR2(20 BYTE), 
	"NATIV" VARCHAR2(20 BYTE), 
	"TELE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(30 BYTE), 
	"HEIGHT" VARCHAR2(20 BYTE), 
	"BLOODTYPE" VARCHAR2(10 BYTE), 
	"BIRTHPLACE" VARCHAR2(50 BYTE), 
	"HKPLACE" VARCHAR2(50 BYTE), 
	"DEGREE" VARCHAR2(20 BYTE), 
	"GRADUATESCHOOL" VARCHAR2(50 BYTE), 
	"PROFESSIONAL" VARCHAR2(50 BYTE), 
	"GRADUATETIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.SKEMP
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SKEMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKEMP_PK" ON "SCOTT"."SKEMP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKEMP_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKEMP_UK1" ON "SCOTT"."SKEMP" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKEMP_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKEMP_UK2" ON "SCOTT"."SKEMP" ("IDCARD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SKEMP
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKEMP" ADD CONSTRAINT "SKEMP_UK2" UNIQUE ("IDCARD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKEMP" ADD CONSTRAINT "SKEMP_UK1" UNIQUE ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKEMP" ADD CONSTRAINT "SKEMP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("ZZMM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("TOWORKTIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("IDCARD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("BIR" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKEMP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger SKEMP_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKEMP_TRG" BEFORE INSERT ON SKEMP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKEMP_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKEMP_TRG" ENABLE;
