--------------------------------------------------------
--  文件已创建 - 星期六-九月-19-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SKJOB
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SKJOB" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"LIMITNUM" VARCHAR2(10 BYTE), 
	"DEPT_ID" VARCHAR2(10 BYTE), 
	"ISLIMIT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.SKJOB
SET DEFINE OFF;
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (1,'行政总监','1','Manage','3','2','Yes');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (2,'行政主管','2','Manage','10','4','Yes');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (3,'技术开发','3','Technology','40','4','No');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (4,'销售总监','4','Marketing','30','5','No');
Insert into SCOTT.SKJOB (ID,NAME,JOB_ID,TYPE,LIMITNUM,DEPT_ID,ISLIMIT) values (5,'财务总管','5','Market','10','6','Yes');
--------------------------------------------------------
--  DDL for Index SKJOB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKJOB_PK" ON "SCOTT"."SKJOB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SKJOB_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SKJOB_UK1" ON "SCOTT"."SKJOB" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SKJOB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("ISLIMIT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" ADD CONSTRAINT "SKJOB_UK1" UNIQUE ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKJOB" ADD CONSTRAINT "SKJOB_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("DEPT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("LIMITNUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SKJOB" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SKJOB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SKJOB" ADD CONSTRAINT "SKJOB_SKDEPT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "SCOTT"."SKDEPT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKJOB_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."SKJOB_TRG" BEFORE INSERT ON SKJOB 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SKJOB_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."SKJOB_TRG" ENABLE;
